routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', function () {
    return view('welcome');
});

Route::resource('/index','indexController');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['namespace'=>'Administrator','prefix'=>'admin'],function (){

    Route::resource('panel','panelController');

    Route::resource('user','userController');

    Route::get('slider','sliderController@show');

    Route::post('save','sliderController@save');

    Route::get('comment','commentController@show');

    Route::patch('agree','commentController@update');

    Route::delete('remove','commentController@remove');

    Route::resource('category','catController');

    Route::resource('new','newController');

    Route::patch('update','newsController@refresh');

    Route::resource('tab','tabController');

    Route::resource('report','repotimageController');

    Route::patch('reupdate','reController@update');

    Route::resource('login','loginController');

    Route::resource('profile','profileController');

    Route::resource('menu','menuController');

    Route::resource('submenu','submenuController');

    Route::PATCH('disable','menuactiveController@disable');

    Route::PATCH('enable','menuactiveController@enable');

    Route::PATCH('enablesub','subactiveController@enable');

    Route::PATCH('disablesub','subactiveController@disable');

    Route::resource('workgroup','workgroupController');

    Route::PATCH('active','workController@active');

    Route::PATCH('deactive','workController@deactive');

    Route::post('premesion','premesionController@store');

    Route::get('getpdf','pdfController@getpdf');

    Route::get("fullcalendar", "Calender@Chartjs");

    Route::resource("connect", "contectusController");

    Route::resource("view","viewController");

});

app/Http/Controllers/Administrator/tabController.php
<?php

namespace App\Http\Controllers\Administrator;

use App\Http\Controllers\Controller;
use App\Http\Requests\tablrequest;
use App\newModel;
use App\tabModel;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class tabController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $u=Auth::user()->id;
        $item_name=DB::table('auth_assignment')->select('item_name')->where("user_id","=",$u)->first()->item_name;
        $menu_count=DB::table('auth_item_child')->where("item_name","=",$item_name)->where("child" ,"=", "view@2")->count();
        if($menu_count != 0) {
        $tab=tabModel::latest()->paginate(5);
        return view('admin.tab.list_tab',compact('tab'));
        }else{
            echo '<img src="../../../images/pre/1.jpg" class="imgpre" style="margin-left:265px;margin-top:60px;border-radius: 80px;">';
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $u=Auth::user()->id;
        $item_name=DB::table('auth_assignment')->select('item_name')->where("user_id","=",$u)->first()->item_name;
        $menu_count=DB::table('auth_item_child')->where("item_name","=",$item_name)->where("child" ,"=", "create@2")->count();
        if($menu_count != 0) {
        return view('admin.tab.add_tab');
        }else{
            echo '<img src="../../../images/pre/1.jpg" class="imgpre" style="margin-left:265px;margin-top:60px;border-radius: 80px;">';
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $record = new tabModel();
        if($request->hasFile('imgpic')){
            $filename = Time().'.'.$request->file('imgpic')->getClientOriginalExtension();
            if ($request->file('imgpic')->move('images/tablighat', $filename)) {
                $record->imgpic = $filename;
            }
        }
        $record->text=$request->input('text');
        $record->save();
        alert()->success('موفقیت امیز','با موفقیت درج  شد');
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request)
    {
        $delt=tabModel::FindOrFail($request->explain_tab);
        return view('admin.tab.explain_tab',compact('delt'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(tabModel $tab)
    {
        $u=Auth::user()->id;
        $item_name=DB::table('auth_assignment')->select('item_name')->where("user_id","=",$u)->first()->item_name;
        $menu_count=DB::table('auth_item_child')->where("item_name","=",$item_name)->where("child" ,"=", "create@2")->count();
        if($menu_count != 0) {
            return view( 'admin.tab.edit_tab' , compact( 'tab' ) );
        }else{
            echo '<img src="../../../images/pre/1.jpg" class="imgpre" style="margin-left:265px;margin-top:60px;border-radius: 80px;">';
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, tabModel $tab)
    {
        $record=$request->all();
        if($request->hasFile('imgpic')){
            $filename = Time().'.'.$request->file('imgpic')->getClientOriginalExtension();
            if ($request->file('imgpic')->move('images/tablighat', $filename)) {
                $record['imgpic'] = $filename;
            }
        }
        $tab->update($record);
        alert()->success('موفقیت امیز','با موفقیت بروزرسانی شد  شد');
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(tabModel $tab)
    {
        $tab->delete();
        alert()->success('موفقیت امیز','با موفقیت حذف  شد');
        return redirect()->back();

    }
}

resources/views/admin/tab/add_tab.blade.php
@extends('layout.index')
@section('css')
    <style type="text/css">
        body {
            font-family: sans-serif;
            background-color: #eeeeee;
        }

        .file-upload {
            background-color: #ffffff;
            width: 600px;
            margin: 0 auto;
            padding: 20px;
        }

        .file-upload-btn {
            width: 100%;
            margin: 0;
            color: #fff;
            background: #1FB264;
            border: none;
            padding: 10px;
            border-radius: 4px;
            border-bottom: 4px solid #15824B;
            transition: all .2s ease;
            outline: none;
            text-transform: uppercase;
            font-weight: 700;
        }

        .file-upload-btn:hover {
            background: #1AA059;
            color: #ffffff;
            transition: all .2s ease;
            cursor: pointer;
        }

        .file-upload-btn:active {
            border: 0;
            transition: all .2s ease;
        }

        .file-upload-content {
            display: none;
            text-align: center;
        }

        .file-upload-input {
            position: absolute;
            margin: 0;
            padding: 0;
            width: 100%;
            height: 100%;
            outline: none;
            opacity: 0;
            cursor: pointer;
        }

        .image-upload-wrap {
            margin-top: 20px;
            border: 4px dashed #1FB264;
            position: relative;
        }

        .image-dropping,
        .image-upload-wrap:hover {
            background-color: #1FB264;
            border: 4px dashed #ffffff;
        }

        .image-title-wrap {
            padding: 0 15px 15px 15px;
            color: #222;
        }

        .drag-text {
            text-align: center;
        }

        .drag-text h3 {
            font-weight: 100;
            text-transform: uppercase;
            color:black;
            padding: 60px 0;
        }

        .file-upload-image {
            max-height: 200px;
            max-width: 200px;
            margin: auto;
            padding: 20px;
        }

        .remove-image {
            width: 200px;
            margin: 0;
            color: #fff;
            background: #cd4535;
            border: none;
            padding: 10px;
            border-radius: 4px;
            border-bottom: 4px solid #b02818;
            transition: all .2s ease;
            outline: none;
            text-transform: uppercase;
            font-weight: 700;
        }

        .remove-image:hover {
            background: #c13b2a;
            color: #ffffff;
            transition: all .2s ease;
            cursor: pointer;
        }

        .remove-image:active {
            border: 0;
            transition: all .2s ease;
        }
    </style>
    <script type="text/javascript">
        function readURL(input) {
            if (input.files && input.files[0]) {

                var reader = new FileReader();

                reader.onload = function(e) {
                    $('.image-upload-wrap').hide();

                    $('.file-upload-image').attr('src', e.target.result);
                    $('.file-upload-content').show();

                    $('.image-title').html(input.files[0].name);
                };

                reader.readAsDataURL(input.files[0]);

            } else {
                removeUpload();
            }
        }

        function removeUpload() {
            $('.file-upload-input').replaceWith($('.file-upload-input').clone());
            $('.file-upload-content').hide();
            $('.image-upload-wrap').show();
        }
        $('.image-upload-wrap').bind('dragover', function () {
            $('.image-upload-wrap').addClass('image-dropping');
        });
        $('.image-upload-wrap').bind('dragleave', function () {
            $('.image-upload-wrap').removeClass('image-dropping');
        });
    </script>
@endsection

@section('content')
    <div class="row">
    <div class="col-sm-6" >
        {{Form::open(array('action'=>'Administrator\tabController@store','files'=>true,'class'=>'fouser'))}}
        <div class="card">
            <form action="" method="post" class="" enctype="multipart/form-data">
                <div class="card-header">
                    <strong>افزودن تبلیغات</strong>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        {{Form::label('inputname','بنر تبلیغات')}}<i class="fa fa-star" style="font-size: 10px;color: red"></i>

                        <div class="image-upload-wrap">

                            <input class="file-upload-input" type='file' name="imgpic" onchange="readURL(this);" accept="image/*" />
                            <div class="drag-text">
                                <h3><i class="fa fa-upload" aria-hidden="true" style="font-size: 50px;"></i>
                                </h3>
                            </div>
                        </div>
                        <div class="file-upload-content">
                            <img class="file-upload-image" src="#" alt="your image" />
                            <div class="image-title-wrap">
                                <button type="button" onclick="removeUpload()" class="remove-image">حذف <span class="image-title">Uploaded Image</span></button>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 float-right">
                        {{Form::label('inputtext','نام تبلیغات:')}}<i class="fa fa-star" style="font-size: 10px;color: red"></i>
                        <br>
                        {{Form::text('text',null,['placeholder'=>'نام تبلیغات ......','class'=>'form-control'])}}
                    </div>

                    <!--/.row-->

                    <div class="col-lg-6 float-left" style="position: relative;top: 26px;right:130px">
                        {{Form::button('<i class="fa fa-send"></i>ارسال',['type'=>'submit','class'=>'btn btn-success'])}}
                        {{Form::button('<i class="fa fa-close"></i>انصراف',['type'=>'reset','class'=>'btn btn-danger'])}}

                    </div>
                </div>
            </form>
        </div>

    </div>
    </div>
@endsection

resources/views/admin/tab/edit_tab.blade.php
@extends('layout.index')
@section('css')
    <style type="text/css">
        body {
            font-family: sans-serif;
            background-color: #eeeeee;
        }

        .file-upload {
            background-color: #ffffff;
            width: 600px;
            margin: 0 auto;
            padding: 20px;
        }

        .file-upload-btn {
            width: 100%;
            margin: 0;
            color: #fff;
            background: #1FB264;
            border: none;
            padding: 10px;
            border-radius: 4px;
            border-bottom: 4px solid #15824B;
            transition: all .2s ease;
            outline: none;
            text-transform: uppercase;
            font-weight: 700;
        }

        .file-upload-btn:hover {
            background: #1AA059;
            color: #ffffff;
            transition: all .2s ease;
            cursor: pointer;
        }

        .file-upload-btn:active {
            border: 0;
            transition: all .2s ease;
        }

        .file-upload-content {
            display: none;
            text-align: center;
        }

        .file-upload-input {
            position: absolute;
            margin: 0;
            padding: 0;
            width: 100%;
            height: 100%;
            outline: none;
            opacity: 0;
            cursor: pointer;
        }

        .image-upload-wrap {
            margin-top: 20px;
            border: 4px dashed #1FB264;
            position: relative;
        }

        .image-dropping,
        .image-upload-wrap:hover {
            background-color: #1FB264;
            border: 4px dashed #ffffff;
        }

        .image-title-wrap {
            padding: 0 15px 15px 15px;
            color: #222;
        }

        .drag-text {
            text-align: center;
        }

        .drag-text h3 {
            font-weight: 100;
            text-transform: uppercase;
            color:black;
            padding: 60px 0;
        }

        .file-upload-image {
            max-height: 200px;
            max-width: 200px;
            margin: auto;
            padding: 20px;
        }

        .remove-image {
            width: 200px;
            margin: 0;
            color: #fff;
            background: #cd4535;
            border: none;
            padding: 10px;
            border-radius: 4px;
            border-bottom: 4px solid #b02818;
            transition: all .2s ease;
            outline: none;
            text-transform: uppercase;
            font-weight: 700;
        }

        .remove-image:hover {
            background: #c13b2a;
            color: #ffffff;
            transition: all .2s ease;
            cursor: pointer;
        }

        .remove-image:active {
            border: 0;
            transition: all .2s ease;
        }
    </style>
    <script type="text/javascript">
        function readURL(input) {
            if (input.files && input.files[0]) {

                var reader = new FileReader();

                reader.onload = function(e) {
                    $('.image-upload-wrap').hide();

                    $('.file-upload-image').attr('src', e.target.result);
                    $('.file-upload-content').show();

                    $('.image-title').html(input.files[0].name);
                };

                reader.readAsDataURL(input.files[0]);

            } else {
                removeUpload();
            }
        }

        function removeUpload() {
            $('.file-upload-input').replaceWith($('.file-upload-input').clone());
            $('.file-upload-content').hide();
            $('.image-upload-wrap').show();
        }
        $('.image-upload-wrap').bind('dragover', function () {
            $('.image-upload-wrap').addClass('image-dropping');
        });
        $('.image-upload-wrap').bind('dragleave', function () {
            $('.image-upload-wrap').removeClass('image-dropping');
        });
    </script>
@endsection

@section('content')
    <div class="row">
    <div class="col-sm-6">
        {{Form::open(array('url'=>route('tab.update',$tab->id),'files'=>true,'class'=>'fouser'))}}
        {{@method_field('PATCH')}}
        <div class="card">
            <form action="" method="post" class="" enctype="multipart/form-data">
                <div class="card-header">
                    <strong>افزودن تبلیغات</strong>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        {{Form::label('inputname','بنر تبلیغات')}}<i class="fa fa-star" style="font-size: 10px;color: red"></i>

                        <div class="image-upload-wrap">

                            <input class="file-upload-input" type='file' name="imgpic" onchange="readURL(this);" accept="image/*" />
                            <div class="drag-text">
                                <h3><i class="fa fa-upload" aria-hidden="true" style="font-size: 50px;"></i>
                                </h3>
                            </div>
                        </div>
                        <div class="file-upload-content">
                            <img class="file-upload-image" src="#" alt="your image" />
                            <div class="image-title-wrap">
                                <button type="button" onclick="removeUpload()" class="remove-image">حذف <span class="image-title">Uploaded Image</span></button>
                            </div>
                            <img src="../../../images/tablighat/{{$tab->imgpic}}" alt="" width="50" height="50">

                        </div>
                    </div>
                    <div class="col-lg-6 float-right">
                        {{Form::label('inputtext','نام تبلیغات:')}}
                        <br>
                        {{Form::text('text',$tab->text,['placeholder'=>'نام تبلیغات ......','class'=>'form-control'])}}                    </div>

                    <!--/.row-->

                    <div class="col-lg-6 float-left" style="position: relative;top: 26px;right:130px">
                        {{Form::button('<i class="fa fa-send"></i>ارسال',['type'=>'submit','class'=>'btn btn-success'])}}
                        {{Form::button('<i class="fa fa-close"></i>انصراف',['type'=>'reset','class'=>'btn btn-danger'])}}

                    </div>
                </div>
            </form>
        </div>

    </div>
    </div>
@endsection

resources/views/admin/tab/explain_tab.blade.php
@extends('layout.index')
@section('content')

    <div class="row" style="width: 100%;height: 100%;position: relative;right:16px;font-family: 'B Yekan';font-size:20px;color: #000;">
        <div class="col-lg-12 bg-white">
            <p style="text-align: right;padding-right: 8px;padding-top:8px;box-sizing: border-box">جزئیات تبلیغات</p>
            <hr>
            <div class="col-lg-6 float-right" style="padding-top: 20px;box-sizing: border-box">
                <label for="">نام تبلیغات:{{$delt->text}}</label>
            </div>
            <div class="col-lg-6 float-left" style="padding-top: 20px;box-sizing: border-box">
                <label for="">تصویر تبلیغات:<img src="../../../images/tablighat/{{$delt->imgpic}}" alt="" width="50" height="50">   </label>
            </div>
            <div class="col-lg-6 float-left" style="padding-top: 20px;box-sizing: border-box">
                <form action="\admin\tab\" style="position:relative;right:1000px;top: 50px;">
                    <button class="btn btn-primary" style="border-radius: 5px">بازگشت</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/tab/list_tab.blade.php
@extends('layout.index')
@section('script')
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="<?php echo url('../js/sort-table.js')?>"></script>
    <script src="<?php echo url('../js/sort-table.min.js')?>"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script>
        $(document).ready(function(){
            $("#myInput").on("keyup", function() {
                var value = $(this).val().toLowerCase();
                $("#myTable tr").filter(function() {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>


@endsection
@section('content')
    <div class="card">

        <div class="card-header">
            <h3 class="card-title" style="font-family: 'B Yekan';text-align: right;"><i class="fa fa-list-alt" style="position: relative;top: 2px;left: 4px;"></i>لیست تبلیغات</h3>

            <a href="\admin\tab\create"><button type="button" class="bg bg-success" style="border-radius: 5px;"> <i class="fa fa-plus" aria-hidden="true"></i></button></a>



        </div>
        <!-- /.card-header -->

        <div class="card-body">
            <div class="row">

                <div class="col-lg-6" style="float: left!important;">
                    <input class="form-control" id="myInput" type="text" placeholder="جستجو...." style="margin-bottom: 20px;font-family: 'B Yekan'">
                </div>
            </div>
            <?php $tbl=DB::table('advertising')->get(); ?>
            @if(count($tbl)>=1)
                <table  class="table table-bordered table-striped js-sort-table"  id="demo1">
                    <thead>
                    <tr>
                        <th>کد تبلیغات</th>
                        <th>عکس</th>
                        <th>متن</th>
                        <th>عملیات</th>
                    </tr>
                    </thead>

                    <tbody id="myTable" class="sortable">
                    @foreach($tab as $tablighat)
                    <tr>
                    <td>{{$tablighat->id}}</td>
                    <td><img src="../../../images/tablighat/{{$tablighat->imgpic}}" width="80" height="80" alt=""></td>
                    <td>{{$tablighat->text}}</td>
                    <td style="width: 12%">
                    <form action="{{route('tab.edit',$tablighat->id)}}"  style="width: 2%;">
                    <button type="submit" class="btn btn-success" style="border-radius: 5px">
                    <i class="fa fa-edit"></i>
                    </button>
                    </form>
                    <form action="{{route('tab.destroy',$tablighat->id)}}" id="closee" method="post" style="width: 2%;">
                    {{@method_field('delete')}}
                    {{@csrf_field()}}
                    <button type="submit" class="btn btn-danger" style="border-radius: 5px;position: relative;top: 13px;">
                    <i class="fa fa-trash-o"></i>
                    </button>
                    </form>
                        <form action="/admin/tab/show" id="closee" method="get" style="width: 2%;">
                            {{@method_field('get')}}
                            {{@csrf_field()}}
                            <input type="hidden" name="explain_tab" value="{{$tablighat->id}}">
                            <button type="submit" class="btn btn-primary" style="border-radius: 5px;position: relative;top:-22px;right: 46px;">
                                <i class="fa fa-eye"></i>
                            </button>
                        </form>
                    </td>
                    </tr>
                    @endforeach
                    </tbody>
                    <tfoot>
                    <tr>
                        <th>کد تبلیغات</th>
                        <th>عکس</th>
                        <th>متن</th>
                        <th>عملیات</th>
                    </tr>
                    </tfoot>
                </table>
            @else
                <p style="font-family: 'B Yekan'">چیزی برای نمایش وجود ندارد</p>
            @endif
        </div>
        <ul class="pagination">
            {{$tab->links()}}
        </ul>
        <!-- /.card-body -->
    </div>

@stop