routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', function () {
    return view('welcome');
});

Route::resource('/index','indexController');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['namespace'=>'Administrator','prefix'=>'admin'],function (){

    Route::resource('panel','panelController');

    Route::resource('user','userController');

    Route::get('slider','sliderController@show');

    Route::post('save','sliderController@save');

    Route::get('comment','commentController@show');

    Route::patch('agree','commentController@update');

    Route::delete('remove','commentController@remove');

    Route::resource('category','catController');

    Route::resource('new','newController');

    Route::patch('update','newsController@refresh');

    Route::resource('tab','tabController');

    Route::resource('report','repotimageController');

    Route::patch('reupdate','reController@update');

    Route::resource('login','loginController');

    Route::resource('profile','profileController');

    Route::resource('menu','menuController');

    Route::resource('submenu','submenuController');

    Route::PATCH('disable','menuactiveController@disable');

    Route::PATCH('enable','menuactiveController@enable');

    Route::PATCH('enablesub','subactiveController@enable');

    Route::PATCH('disablesub','subactiveController@disable');

    Route::resource('workgroup','workgroupController');

    Route::PATCH('active','workController@active');

    Route::PATCH('deactive','workController@deactive');

    Route::post('premesion','premesionController@store');

    Route::get('getpdf','pdfController@getpdf');

    Route::get("fullcalendar", "Calender@Chartjs");

    Route::resource("connect", "contectusController");

    Route::resource("view","viewController");

});

app/EventModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class EventModel extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','picture'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    function admin(){
        return $this->role=='admin' ? true : false;
    }


}

app/authModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class authModel extends Model
{
   protected $table='auth_item_child';
   public $timestamps=false;
    protected $fillable=['ID','item_name','child'];

}

app/categoryModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class categoryModel extends Model
{

    protected $table='category';
    protected $fillable=['id','name'];

    public function news(){
        return $this->belongsTo(newsModel::class);
    }
}

app/commentModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class commentModel extends Model
{
    protected $table='comments';
    protected $fillable=['id','name','user_id','accept','context'];


}

app/contect.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class contect extends Model
{
    protected $table="contact_us";
    public $timestamps=false;
    protected $fillable=['ID','name','family','email','phone','content'];

}

app/faModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class faModel extends Model
{
    protected $table="fa";
    protected $fillable=['id','name'];
}

app/loginModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class loginModel extends Model
{
    protected $table="login_config";
    protected $fillable=['id','title','logo','copyright'];
}

app/menuModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class menuModel extends Model
{
    protected $table="menu";
    protected $fillable=['id','titleme','title_en','routeme','icon_classme','status'];
}

app/newModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;


class newModel extends Model
{

    use Sluggable;

    protected $table="news";
    protected $fillable=['id','title','slug','date','time','user','context','image','category','status'];
    public function news(){
        return $this->belongsTo(categoryModel::class);
    }
    public function Sluggable(){
        return[
            'slug'=>[
                'source'=>'title'
            ]
        ];
    }
    public function path(){
        return "/index/$this->slug";
    }
}

app/premesionModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class premesionModel extends Model
{
    protected $table="auth_assignment";
    public $timestamps = false;
    protected $fillable=['id','item_name','user_id'];
}

app/reportimageModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class reportimageModel extends Model
{
    protected $table="reportimage";
    protected $fillable=['id','name','date','time','user','picture','status'];
}

app/slideModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class slideModel extends Model
{
    protected $table='slider';
    protected $fillable=['id','img'];

}

app/submenumodel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class submenumodel extends Model
{
    protected $table="subsystem";
    protected $fillable=['id','title','title_en','menu_id','route','status'];

    public function menu(){
        $this->belongsTo(menuModel::class);
    }
}

app/tabModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class tabModel extends Model
{
    protected $table="Advertising";
    protected $fillable=['id','imgpic', 'text'];
}

app/viewModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class viewModel extends Model
{
    protected $table="view";
    public $timestamps=false;
    protected $fillable=['ID','news_id','view'];
}

app/workgroupModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class workgroupModel extends Model
{
    protected $table="auth_item_date";
    protected $fillable=['item_name','title','status'];
}

app/workmenuModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class workmenuModel extends Model
{

    protected $table="auth_menu";
    protected $fillable=['id','item_name','menu_id'];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        include(app_path() . '\Classes\phpgrid\jqgrid_dist.php');

        // Database config file to be passed in phpgrid constructor
        $db_conf = array(
            "type" 		=> 'mysqli',
            "server" 	=> 'localhost',
            "user" 		=> 'root',
            "password" 	=> '',
            "database" 	=> 'lara'
        );

        $g = new \jqgrid($db_conf);

        $opt["caption"] = "Sample Grid";
        $g->set_options($opt);

        $g->table = "category";

        $out = $g->render("list1");

        return view('welcome',array('phpgrid_output'=>$out));
    }

}

resources/views/admin/contact/add_contect.blade.php
@extends('layout.index')
@section('content')
    <div class="row">
        <div class="col-sm-6" id="form">
            {{Form::open(array('url'=>route('connect.update',$connect->ID),'class'=>'fouser'))}}
            {{@method_field('PATCH')}}

            <div class="card" >
                <form action="" method="post">
                    <div class="card-header">
                        <small></small>
                        <strong>ویرایش تماس با ما</strong>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            {{Form::label('inputname','نام')}}<i class="fa fa-star" style="font-size: 10px;color: red"></i>
                            {{Form::text('name',$connect->name,['class'=>'form-control'])}}
                        </div>
                        <div class="form-group">
                            {{Form::label('inputname','فامیل')}}<i class="fa fa-star" style="font-size: 10px;color: red"></i>
                            {{Form::text('family',$connect->family,['class'=>'form-control'])}}
                        </div>
                        <div class="form-group">
                            {{Form::label('inputname','ایمیل')}}<i class="fa fa-star" style="font-size: 10px;color: red"></i>
                            {{Form::text('email',$connect->email,['class'=>'form-control'])}}
                        </div>
                        <div class="form-group">
                            {{Form::label('inputname','تلفن')}}
                            {{Form::text('phone',$connect->phone,['class'=>'form-control'])}}
                        </div>
                        <div class="form-group">
                            {{Form::label('inputname','محتوا')}}
                            {{Form::text('content',$connect->content,['class'=>'form-control'])}}
                        </div>
                        <div class="form-group">
                            {{Form::button('<i class="fa fa-send"></i> ارسال',['type'=>'submit','class'=>'btn btn-sm btn-primary'])}}
                            {{Form::button('<i class="fa fa-close"></i> انصراف',['type'=>'reset','class'=>'btn btn-sm btn-danger'])}}
                        </div>
                        <!--/.row-->

                    </div>
                </form>
                {{Form::close()}}
            </div>

        </div>

    </div>
@endsection

resources/views/admin/contact/list_contact.blade.php
@extends('layout.index')
@section('script')
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="<?php echo url('../js/sort-table.js')?>"></script>
    <script src="<?php echo url('../js/sort-table.min.js')?>"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script>
        $(document).ready(function(){
            $("#myInput").on("keyup", function() {
                var value = $(this).val().toLowerCase();
                $("#myTable tr").filter(function() {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>


@endsection
@section('content')
    <div class="card">

        <div class="card-header">
            <h3 class="card-title" style="font-family: 'B Yekan';text-align: right;"><i class="fa fa-list-alt" style="position: relative;top: 2px;left: 4px;"></i>لیست تماس با ما</h3>




        </div>
        <!-- /.card-header -->

        <div class="card-body">
            <div class="row">

                <div class="col-lg-6" style="float: left!important;">
                    <input class="form-control" id="myInput" type="text" placeholder="جستجو...." style="margin-bottom: 20px;font-family: 'B Yekan'">
                </div>
            </div>
            <?php $tbl=DB::table('contact_us')->get(); ?>
            @if(count($tbl)>=1)
                <table  class="table table-bordered table-striped js-sort-table"  id="demo1">
                    <thead>
                    <tr>
                        <th>کد</th>
                        <th>نام</th>
                        <th>فامیل</th>
                        <th>ایمیل</th>
                        <th>تلفن</th>
                        <th>محتوا</th>
                        <th>عملیات</th>
                    </tr>
                    </thead>

                    <tbody id="myTable" class="sortable">
                    @foreach($connect as $co)
                        <tr>
                            <td>{{$co->ID}}</td>
                            <td>{{$co->name}}</td>
                            <td>{{$co->family}}</td>
                            <td>{{$co->email}}</td>
                            <td>{{$co->phone}}</td>
                            <td>{{$co->content}}</td>
                            <td style="width:150px">
                                <form action="{{route('connect.edit',$co->ID)}}" style="width: 2%;">
                                    <button type="submit" class="btn btn-success btnf" style="border-radius: 5px;position: relative;top: 12px;">
                                        <i class="fa fa-edit"></i>
                                    </button>
                                </form>
                                <form action="{{route('connect.destroy',$co->ID)}}" id="closee" method="post" style="width: 2%;">
                                    {{@method_field('delete')}}
                                    {{@csrf_field()}}
                                    <button type="submit" class="btn btn-danger btnd" style="border-radius: 5px;position: relative;top: 25px;">
                                        <i class="fa fa-trash-o"></i>
                                    </button>
                                </form>

                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                    <tfoot>
                    <tr>
                        <th>کد</th>
                        <th>نام</th>
                        <th>فامیل</th>
                        <th>ایمیل</th>
                        <th>تلفن</th>
                        <th>محتوا</th>
                        <th>عملیات</th>
                    </tr>
                    </tfoot>
                </table>
            @else
                <p style="font-family: 'B Yekan'">چیزی برای نمایش وجود ندارد</p>
            @endif
        </div>
        <ul class="pagination">

        </ul>
        <!-- /.card-body -->
    </div>

@stop

resources/views/admin/reportimage/explain_report.blade.php
@extends('layout.index')
@section('content')

    <div class="row" style="width: 100%;height: 100%;position: relative;right:16px;font-family: 'B Yekan';font-size:20px;color: #000;">
        <div class="col-lg-12 bg-white">
            <p style="text-align: right;padding-right: 8px;padding-top:8px;box-sizing: border-box">گزارش تصویری</p>
            <hr>
            <div class="col-lg-6 float-right" style="padding-top: 20px;box-sizing: border-box">
                <label for="">نام گزارش تصویری:{{$re->name}}</label>
            </div>
                <div class="col-lg-6 float-right" style="padding-top: 20px;box-sizing: border-box">
                    <label for="">تصویر گزارش تصویری:<img src="../../../images/reportimage/{{$re->picture}}" alt="" width="50" height="50">   </label>
                </div>
            <div class="col-lg-6 float-left" style="padding-top: 20px;box-sizing: border-box">
                <form action="\admin\report\" style="position:relative;right:500px;top: 50px;">
                    <button class="btn btn-primary" style="border-radius: 5px">بازگشت</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/reportimage/report_edit.blade.php
@extends('layout.index')
@section('css')
    <style type="text/css">
        body {
            font-family: sans-serif;
            background-color: #eeeeee;
        }

        .file-upload {
            background-color: #ffffff;
            width: 600px;
            margin: 0 auto;
            padding: 20px;
        }

        .file-upload-btn {
            width: 100%;
            margin: 0;
            color: #fff;
            background: #1FB264;
            border: none;
            padding: 10px;
            border-radius: 4px;
            border-bottom: 4px solid #15824B;
            transition: all .2s ease;
            outline: none;
            text-transform: uppercase;
            font-weight: 700;
        }

        .file-upload-btn:hover {
            background: #1AA059;
            color: #ffffff;
            transition: all .2s ease;
            cursor: pointer;
        }

        .file-upload-btn:active {
            border: 0;
            transition: all .2s ease;
        }

        .file-upload-content {
            display: none;
            text-align: center;
        }

        .file-upload-input {
            position: absolute;
            margin: 0;
            padding: 0;
            width: 100%;
            height: 100%;
            outline: none;
            opacity: 0;
            cursor: pointer;
        }

        .image-upload-wrap {
            margin-top: 20px;
            border: 4px dashed #1FB264;
            position: relative;
        }

        .image-dropping,
        .image-upload-wrap:hover {
            background-color: #1FB264;
            border: 4px dashed #ffffff;
        }

        .image-title-wrap {
            padding: 0 15px 15px 15px;
            color: #222;
        }

        .drag-text {
            text-align: center;
        }

        .drag-text h3 {
            font-weight: 100;
            text-transform: uppercase;
            color:black;
            padding: 60px 0;
        }

        .file-upload-image {
            max-height: 200px;
            max-width: 200px;
            margin: auto;
            padding: 20px;
        }

        .remove-image {
            width: 200px;
            margin: 0;
            color: #fff;
            background: #cd4535;
            border: none;
            padding: 10px;
            border-radius: 4px;
            border-bottom: 4px solid #b02818;
            transition: all .2s ease;
            outline: none;
            text-transform: uppercase;
            font-weight: 700;
        }

        .remove-image:hover {
            background: #c13b2a;
            color: #ffffff;
            transition: all .2s ease;
            cursor: pointer;
        }

        .remove-image:active {
            border: 0;
            transition: all .2s ease;
        }
    </style>
    <script type="text/javascript">
        function readURL(input) {
            if (input.files && input.files[0]) {

                var reader = new FileReader();

                reader.onload = function(e) {
                    $('.image-upload-wrap').hide();

                    $('.file-upload-image').attr('src', e.target.result);
                    $('.file-upload-content').show();

                    $('.image-title').html(input.files[0].name);
                };

                reader.readAsDataURL(input.files[0]);

            } else {
                removeUpload();
            }
        }

        function removeUpload() {
            $('.file-upload-input').replaceWith($('.file-upload-input').clone());
            $('.file-upload-content').hide();
            $('.image-upload-wrap').show();
        }
        $('.image-upload-wrap').bind('dragover', function () {
            $('.image-upload-wrap').addClass('image-dropping');
        });
        $('.image-upload-wrap').bind('dragleave', function () {
            $('.image-upload-wrap').removeClass('image-dropping');
        });
    </script>
@endsection
@section('content')

    <div class="row">
        <div class="col-sm-6" id="form">
            {{Form::open(array('url'=>route('report.update',$report->id),'files'=>true,'class'=>'fouser','method'=>'PATCH'))}}

            <div class="card" >
                <form action="" method="post">
                    @if(count($errors) >0)
                        <div class="alert alert-danger">
                            <ul>
                                @foreach($errors->all() as $error)
                                    <li>
                                        {{$error}}
                                    </li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <div class="card-header">
                        <small></small>
                        <strong>اضافه کردن خبرجدید</strong>
                    </div>
                    <div class="card-body">

                        <div class="form-group">
                            {{Form::label('inputname','گزارش تصویری')}}<i class="fa fa-star" style="font-size: 10px;color: red"></i>

                            <div class="image-upload-wrap">

                                <input class="file-upload-input" type='file' name="picture" onchange="readURL(this);" accept="image/*" />
                                <div class="drag-text">
                                    <h3><i class="fa fa-upload" aria-hidden="true" style="font-size: 50px;"></i>
                                    </h3>
                                </div>

                            </div>
                            <div class="file-upload-content">
                                <img class="file-upload-image" src="#" alt="your image" />
                                <div class="image-title-wrap">
                                    <button type="button" onclick="removeUpload()" class="remove-image">حذف <span class="image-title">Uploaded Image</span></button>
                                </div>
                            </div>
                            <img src="../../../images/reportimage/{{$report->picture}}" alt="" width="80" height="80">

                        </div>
                        <div class="form-group">
                            {{Form::hidden('date',date('Y/m/d'))}}
                        </div>
                        <div class="form-group">
                            <?php
                            date_default_timezone_set("Asia/Tehran");
                            ?>
                            {{Form::hidden('time',date('h:i:s'))}}
                        </div>
                        <div class="form-group">
                            {{Form::hidden('user',Auth::user()->name,['class'=>'context'])}}
                        </div>

                        <div class="col-lg-6 float-right">
                            {{Form::label('inputname','نام گزارش')}}
                            {{Form::text('name',$report->name,['class'=>'form-control'])}}
                        </div>
                        <div class="col-lg-6 float-left" style="position: relative;top:30px;right: 480px;">
                            {{Form::button('<i class="fa fa-send"></i> ارسال',['type'=>'submit','class'=>'btn btn-sm btn-primary'])}}

                            {{Form::button('<i class="fa fa-close"></i> انصراف',['type'=>'reset','class'=>'btn btn-sm btn-danger'])}}
                        </div>

                        <!--/.row-->

                    </div>
                </form>
                {{Form::close()}}
            </div>

        </div>

    </div>
@endsection

resources/views/admin/reportimage/report_list.blade.php
@extends('layout.index')
@section('script')
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="<?php echo url('../js/sort-table.js')?>"></script>
    <script src="<?php echo url('../js/sort-table.min.js')?>"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script>
        $(document).ready(function(){
            $("#myInput").on("keyup", function() {
                var value = $(this).val().toLowerCase();
                $("#myTable tr").filter(function() {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>


@endsection
@section('content')
    <div class="card">

        <div class="card-header">
            <h3 class="card-title" style="font-family: 'B Yekan';text-align: right;"><i class="fa fa-list-alt" style="position: relative;top: 2px;left: 4px;"></i>لیست گزارش تصویری</h3>

            <a href="\admin\getpdf"><button type="button" class="bg bg-success" style="border-radius: 5px;"> <i class="fa fa-file-pdf-o" aria-hidden="true"></i></button></a>
            <a href="\admin\report\create"><button type="button" class="bg bg-success" style="border-radius: 5px;"> <i class="fa fa-plus" aria-hidden="true"></i></button></a>



        </div>
        <!-- /.card-header -->

        <div class="card-body">
            <div class="row">

                <div class="col-lg-6" style="float: left!important;">
                    <input class="form-control" id="myInput" type="text" placeholder="جستجو...." style="margin-bottom: 20px;font-family: 'B Yekan'">
                </div>
            </div>
            <?php $tbl=DB::table('reportimage')->get(); ?>
            @if(count($tbl)>=1)
                <table  class="table table-bordered table-striped js-sort-table"  id="demo1">
                    <thead>
                    <tr>
                        <th>کد گزارش </th>
                        <th>نام گزارش </th>
                        <th>تاریخ ثبت </th>
                        <th>زمان ثبت </th>
                        <th>کاربر ثبت </th>
                        <th>تصویر گزارش </th>
                        <th>وضعیت</th>
                        <th>عملیات</th>
                    </tr>
                    </thead>

                    <tbody id="myTable" class="sortable">
                    @foreach($report as $image)
                        <tr>
                            <td>{{$image->id}}</td>
                            <td>{{$image->name}}</td>
                            <td>{{$image->date}}</td>
                            <td>{{$image->time}}</td>
                            <td>{{$image->user}}</td>
                            <td><img src="../../../images/reportimage/{{$image->picture}}" alt="" width="50" height="50"></td>
                            <td>
                                @if($image->status==true)
                                    <span class="badge badge-success">تایید شده</span>
                                @elseif($image->status==false)
                                    <span class="badge badge-danger">تایید  نشده</span>


                                @endif
                            </td>
                            <td style="width: 17%">
                                <form action="{{route('report.edit',$image->id)}}"  style="width: 2%;">
                                    <button type="submit" class="btn btn-success btna" style="border-radius: 5px">
                                        <i class="fa fa-edit"></i>
                                    </button>
                                </form>
                                <form action="{{route('report.destroy',$image->id)}}" id="closee" method="post" style="width: 2%;">
                                    {{@method_field('delete')}}
                                    {{@csrf_field()}}
                                    <button type="submit" class="btn btn-danger btnad" style="border-radius: 5px">
                                        <i class="fa fa-trash-o"></i>
                                    </button>
                                </form>
                                <?php
                                $u=Auth::user()->id;
                                $item_name=DB::table('auth_assignment')->select('item_name')->where("user_id","=",$u)->get();
                                ?>
                                <?php
                                foreach ($item_name as $item):
                                    $i=$item->item_name;
                                endforeach;
                                ?>
                                @if($i=='afMxkYm' xor $i=='JxDIpfx')
                                    <form action="/admin/reupdate/" id="refresh" method="post"   style="width: 2%;">
                                        {{@csrf_field()}}
                                        {{@method_field('patch')}}
                                        <input type="hidden" name="report_id" value="{{$image->id}}">
                                        <button type="submit" class="btn btn-success btnsd" style="border-radius: 5px">
                                            <i class="fa fa-check"></i>
                                        </button>
                                    </form>
                                @endif
                                <form action="/admin/report/show" id="refresh" method="get"   style="width: 2%;">
                                    {{@csrf_field()}}
                                    {{@method_field('get')}}
                                    <input type="hidden" name="explain_report" value="{{$image->id}}">
                                    <button type="submit" class="btn btn-primary btnsd" style="border-radius: 5px;position: relative;top:16px;right:44px;">
                                        <i class="fa fa-eye"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                    <tfoot>
                    <tr>
                        <th>کد گزارش </th>
                        <th>نام گزارش </th>
                        <th>تاریخ ثبت </th>
                        <th>زمان ثبت </th>
                        <th>کاربر ثبت </th>
                        <th>تصویر گزارش </th>
                        <th>وضعیت</th>
                        <th>عملیات</th>
                    </tr>
                    </tfoot>
                </table>
            @else
                <p style="font-family: 'B Yekan'">چیزی برای نمایش وجود ندارد</p>
            @endif
        </div>
        <ul class="pagination">
        </ul>
        <!-- /.card-body -->
    </div>

@stop