routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', function () {
    return view('welcome');
});

Route::resource('/index','indexController');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['namespace'=>'Administrator','prefix'=>'admin'],function (){

    Route::resource('panel','panelController');

    Route::resource('user','userController');

    Route::get('slider','sliderController@show');

    Route::post('save','sliderController@save');

    Route::get('comment','commentController@show');

    Route::patch('agree','commentController@update');

    Route::delete('remove','commentController@remove');

    Route::resource('category','catController');

    Route::resource('new','newController');

    Route::patch('update','newsController@refresh');

    Route::resource('tab','tabController');

    Route::resource('report','repotimageController');

    Route::patch('reupdate','reController@update');

    Route::resource('login','loginController');

    Route::resource('profile','profileController');

    Route::resource('menu','menuController');

    Route::resource('submenu','submenuController');

    Route::PATCH('disable','menuactiveController@disable');

    Route::PATCH('enable','menuactiveController@enable');

    Route::PATCH('enablesub','subactiveController@enable');

    Route::PATCH('disablesub','subactiveController@disable');

    Route::resource('workgroup','workgroupController');

    Route::PATCH('active','workController@active');

    Route::PATCH('deactive','workController@deactive');

    Route::post('premesion','premesionController@store');

    Route::get('getpdf','pdfController@getpdf');

    Route::get("fullcalendar", "Calender@Chartjs");

    Route::resource("connect", "contectusController");

    Route::resource("view","viewController");

});

app/Http/Controllers/Administrator/menuController.php
<?php

namespace App\Http\Controllers\Administrator;

use App\faModel;
use App\Http\Controllers\Controller;
use App\menuModel;
use Illuminate\Http\Request;

class menuController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $menu=menuModel::latest()->paginate(7);
        return view('admin.menu.menu_list',compact('menu'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $fa=faModel::all();
        return view('admin.menu.menu_add',compact('fa'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $record = new menuModel();
        $record->titleme=$request->input('titleme');
        $record->title_en=$request->input('title_en');
        $record->routeme=$request->input('routeme');
        $record->icon_classme=$request->input('icon_classme');
        $record->save();
        alert()->success('موفقیت امیز','با موفقیت درج  شد');
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request)
    {
        $meee=menuModel::FindORFail($request->expalin_menu);
        return view('admin.menu.explain_menu',compact('meee'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(menuModel $menu)
    {
        $fa=faModel::all();
        return view('admin.menu.edit_menu',compact('menu','fa'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, menuModel $menu)
    {
        $record=$request->all();
        $menu->update($record);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(menuModel $menu)
    {
        $menu->delete();
        alert()->success('موفقیت امیز','با موفقیت بروزرسانی  شد');
        return redirect()->back();
    }
}

resources/views/admin/menu/edit_menu.blade.php
@extends('layout.index')
@section('css')
    <link rel="stylesheet" href="<?php echo url('../css/bootstrap-iconpicker.min.css')?>">
    <link rel="stylesheet" type="text/css" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">

@endsection
@section('script')
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script type="text/javascript" src="<?php echo url('../js/bootstrap-iconpicker-iconset-all.js')?>"></script>
    <script type="text/javascript" src="<?php echo url('../js/bootstrap-iconpicker-iconset-all.min.js')?>"></script>
    <script type="text/javascript" src="<?php echo url('../js/bootstrap-iconpicker.bundle.min.js')?>"></script>
    <script type="text/javascript" src="<?php echo url('../js/bootstrap-iconpicker.js')?>"></script>
    <script type="text/javascript" src="<?php echo url('../js/bootstrap-iconpicker.min.js')?>"></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


@endsection
@section('content')

    <div class="row">
        <div class="col-lg-6 col-sm-12 " id="form">
            {{Form::open(array('url'=>route('menu.update',$menu->id),'files'=>true,'class'=>'fouser'))}}
            {{@method_field('PATCH')}}

            <div class="card" >
                <form action="" method="post">
                    @if(count($errors) >0)
                        <div class="alert alert-danger">
                            <ul>
                                @foreach($errors->all() as $error)
                                    <li>
                                        {{$error}}
                                    </li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <div class="card-header">
                        <small></small>
                        <strong>اضافه کردن منو</strong>
                    </div>
                    <div class="card-body">
                        <div class="col-lg-6 col-sm-12 float-right">
                            {{Form::label('inputname','عنوان منو')}}
                            {{Form::text('titleme',$menu->titleme,['class'=>'form-control'])}}
                        </div>
                        <div class="col-lg-6 col-sm-12 float-left">
                            {{Form::label('inputname','عنوان انگلیسی منو')}}
                            {{Form::text('title_en',$menu->title_en,['class'=>'form-control'])}}
                        </div>
                        <div class="col-lg-6 col-sm-12 float-right">
                            {{Form::label('inputname','لینک منو')}}
                            {{Form::text('routeme',$menu->routeme,['class'=>'form-control'])}}
                        </div>
                        <div class="col-lg-6 col-sm-12 float-left">
                            {{Form::label('inputname','ایکن منو')}}
                            <button class="btn btn-secondary form-control" name="icon_classme" role="iconpicker"></button>
                        </div>

                        <div class="col-lg-6 col-sm-12 float-left" style="position: relative;top: 12px;right: 467px;">
                            {{Form::button('<i class="fa fa-send"></i> ارسال',['type'=>'submit','class'=>'btn btn-sm btn-primary'])}}

                            {{Form::button('<i class="fa fa-close"></i> انصراف',['type'=>'reset','class'=>'btn btn-sm btn-danger'])}}
                        </div>

                        <!--/.row-->

                    </div>
                </form>
                {{Form::close()}}
            </div>

        </div>

    </div>
@endsection

resources/views/admin/menu/explain_menu.blade.php
@extends('layout.index')
@section('content')

    <div class="row" style="width: 100%;height: 100%;position: relative;right:16px;font-family: 'B Yekan';font-size:20px;color: #000;">
        <div class="col-lg-12 bg-white">
            <p style="text-align: right;padding-right: 8px;padding-top:8px;box-sizing: border-box">جزئیات  منو :{{$meee->titleme}}</p>
            <hr>
            <div class="col-lg-6 float-left" style="padding-top: 20px;box-sizing: border-box">
                <label for="">عنوان خارجی  منو:{{$meee->title_en}}</label>
            </div>
            <div class="col-lg-6 float-right" style="padding-top: 20px;box-sizing: border-box">
                <label for="">لینک   منو:{{$meee->routeme}}</label>
            </div>
            <div class="col-lg-6 float-right" style="padding-top: 20px;box-sizing: border-box">
                <label for="">ایکون   منو:  <i class="{{$meee->icon_classme}}"></i></label>
            </div>
            <div class="col-lg-6 float-left" style="padding-top: 20px;box-sizing: border-box">
                <form action="\admin\menu\" style="position:relative;right:400px;top: 50px;">
                    <button class="btn btn-primary" style="border-radius: 5px">بازگشت</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/menu/menu_add.blade.php
@extends('layout.index')
@section('css')
    <link rel="stylesheet" href="<?php echo url('../css/bootstrap-iconpicker.min.css')?>">
    <link rel="stylesheet" type="text/css" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">

@endsection
@section('script')
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script type="text/javascript" src="<?php echo url('../js/bootstrap-iconpicker-iconset-all.js')?>"></script>
    <script type="text/javascript" src="<?php echo url('../js/bootstrap-iconpicker-iconset-all.min.js')?>"></script>
    <script type="text/javascript" src="<?php echo url('../js/bootstrap-iconpicker.bundle.min.js')?>"></script>
    <script type="text/javascript" src="<?php echo url('../js/bootstrap-iconpicker.js')?>"></script>
    <script type="text/javascript" src="<?php echo url('../js/bootstrap-iconpicker.min.js')?>"></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


@endsection
@section('content')

    <div class="row">
        <div class="col-lg-6 col-sm-12 " id="form">
            {{Form::open(array('action'=>'Administrator\menuController@store','files'=>true,'class'=>'fouser'))}}

            <div class="card" >
                <form action="" method="post">
                    @if(count($errors) >0)
                        <div class="alert alert-danger">
                            <ul>
                                @foreach($errors->all() as $error)
                                    <li>
                                        {{$error}}
                                    </li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <div class="card-header">
                        <small></small>
                        <strong>اضافه کردن منو</strong>
                    </div>
                    <div class="card-body">
                        <div class="col-lg-6 col-sm-12 float-right">
                            {{Form::label('inputname','عنوان منو')}}
                            {{Form::text('titleme',null,['class'=>'form-control'])}}
                        </div>
                        <div class="col-lg-6 col-sm-12 float-left">
                            {{Form::label('inputname','عنوان انگلیسی منو')}}
                            {{Form::text('title_en',null,['class'=>'form-control'])}}
                        </div>
                        <div class="col-lg-6 col-sm-12 float-right">
                            {{Form::label('inputname','لینک منو')}}
                            {{Form::text('routeme',null,['class'=>'form-control'])}}
                        </div>
                        <div class="col-lg-6 col-sm-12 float-left">
                            {{Form::label('inputname','ایکن منو')}}
                            <button class="btn btn-secondary form-control" name="icon_classme" role="iconpicker"></button>
                        </div>

                        <div class="col-lg-6 col-sm-12 float-left" style="position: relative;top: 12px;right: 467px;">
                            {{Form::button('<i class="fa fa-send"></i> ارسال',['type'=>'submit','class'=>'btn btn-sm btn-primary'])}}

                            {{Form::button('<i class="fa fa-close"></i> انصراف',['type'=>'reset','class'=>'btn btn-sm btn-danger'])}}
                        </div>

                        <!--/.row-->

                    </div>
                </form>
                {{Form::close()}}
            </div>

        </div>

    </div>
@endsection

resources/views/admin/menu/menu_list.blade.php
    @extends('layout.index')
@section('script')
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="<?php echo url('../js/sort-table.js')?>"></script>
    <script src="<?php echo url('../js/sort-table.min.js')?>"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script>
        $(document).ready(function(){
            $("#myInput").on("keyup", function() {
                var value = $(this).val().toLowerCase();
                $("#myTable tr").filter(function() {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>


@endsection
@section('content')
    <div class="card">

        <div class="card-header">
            <h3 class="card-title" style="font-family: 'B Yekan';text-align: right;"><i class="fa fa-list-alt" style="position: relative;top: 2px;left: 4px;"></i>لیست منو</h3>

            <a href="\admin\menu\create"><button type="button" class="bg bg-success" style="border-radius: 5px;"> <i class="fa fa-file-pdf-o" aria-hidden="true"></i></button></a>



        </div>
        <!-- /.card-header -->

        <div class="card-body">
            <div class="row">

                <div class="col-lg-6" style="float: left!important;">
                    <input class="form-control" id="myInput" type="text" placeholder="جستجو...." style="margin-bottom: 20px;font-family: 'B Yekan'">
                </div>
            </div>
            <?php $tbl=DB::table('menu')->get(); ?>
            @if(count($tbl)>=1)
                <table  class="table table-bordered table-striped js-sort-table"  id="demo1">
                    <thead>
                    <tr>
                        <th>کدمنو</th>
                        <th>عنوان منو</th>
                        <th>لینک</th>
                        <th>ایکون</th>
                        <th>وضعیت</th>
                        <th>عملیات</th>
                    </tr>
                    </thead>

                    <tbody id="myTable" class="sortable">
                    @foreach($menu as $me)
                        <tr style="font-family: 'B Yekan';text-align: center;">
                            <td>{{$me->id}}</td>
                            <td>{{$me->titleme}}</td>
                            <td>{{$me->routeme}}</td>
                            <td><i class="{{$me->icon_classme}}"></i></td>
                            <td>
                                @if($me->status==true)
                                    <span class="badge badge-pill badge-success">فعال</span>
                                @elseif($me->status==false)
                                    <span class="badge badge-pill badge-danger">غیرفعال</span>

                                @endif

                            </td>
                            <td style="width:17%">
                                <form action="{{route('menu.destroy',$me->id)}}" id="closee"  method="post" style="width: 2%;">
                                    {{@method_field('delete')}}
                                    {{@csrf_field()}}
                                    <button type="submit" class="btn btn-danger btnli"  style="border-radius: 5px">
                                        <i class="fa fa-trash-o"></i>
                                    </button>
                                </form>
                                <form  action="{{route('menu.edit',$me->id)}}"  style="width: 2%;position: relative;top: 7px;">
                                    <button type="submit" class="btn btn-success btnli" style="border-radius: 5px;">
                                        <i class="fa fa-edit"></i>
                                    </button>
                                </form>
                                @if($me->status==true)
                                    <form  action="/admin/disable/" method="post"  style="width: 2%;position: relative;top: 7px;">
                                        {{@csrf_field()}}
                                        {{@method_field('patch')}}
                                        <input type="hidden" name="disable_id" value="{{$me->id}}">
                                        <button type="submit" class="btn btn-primary btnli"  style="border-radius: 5px;">
                                            <i class="fa fa-check-circle-o"></i>
                                        </button>
                                    </form>

                                @elseif($me->status==false)
                                    <form  action="/admin/enable/" method="post"  style="width: 2%;position: relative;top: 7px;">
                                        {{@csrf_field()}}
                                        {{@method_field('patch')}}
                                        <input type="hidden" name="enable_id" value="{{$me->id}}">
                                        <button type="submit" class="btn btn-success btnli"  style="border-radius: 5px;">
                                            <i class="fa fa-check-circle-o"></i>
                                        </button>
                                    </form>

                                @endif
                                <form  action="/admin/menu/show" method="get"  style="width: 2%;position: relative;top: 7px;">
                                    {{@csrf_field()}}
                                    {{@method_field('get')}}
                                    <input type="hidden" name="expalin_menu" value="{{$me->id}}">
                                    <button type="submit" class="btn btn-success btnli"  style="border-radius: 5px;position: relative;top: -69px;right: 141px;">
                                        <i class="fa fa-eye"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach

                    </tbody>
                    <tfoot>
                    <tr>
                        <th>کدمنو</th>
                        <th>عنوان منو</th>
                        <th>لینک</th>
                        <th>ایکون</th>
                        <th>وضعیت</th>
                        <th>عملیات</th>
                    </tr>
                    </tfoot>
                </table>
            @else
                <p style="font-family: 'B Yekan'">چیزی برای نمایش وجود ندارد</p>
            @endif
        </div>
        <ul class="pagination">
            {{$menu->links()}}
        </ul>
        <!-- /.card-body -->
    </div>

@stop