routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', function () {
    return view('welcome');
});

Route::resource('/index','indexController');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['namespace'=>'Administrator','prefix'=>'admin'],function (){

    Route::resource('panel','panelController');

    Route::resource('user','userController');

    Route::get('slider','sliderController@show');

    Route::post('save','sliderController@save');

    Route::get('comment','commentController@show');

    Route::patch('agree','commentController@update');

    Route::delete('remove','commentController@remove');

    Route::resource('category','catController');

    Route::resource('new','newController');

    Route::patch('update','newsController@refresh');

    Route::resource('tab','tabController');

    Route::resource('report','repotimageController');

    Route::patch('reupdate','reController@update');

    Route::resource('login','loginController');

    Route::resource('profile','profileController');

    Route::resource('menu','menuController');

    Route::resource('submenu','submenuController');

    Route::PATCH('disable','menuactiveController@disable');

    Route::PATCH('enable','menuactiveController@enable');

    Route::PATCH('enablesub','subactiveController@enable');

    Route::PATCH('disablesub','subactiveController@disable');

    Route::resource('workgroup','workgroupController');

    Route::PATCH('active','workController@active');

    Route::PATCH('deactive','workController@deactive');

    Route::post('premesion','premesionController@store');

    Route::get('getpdf','pdfController@getpdf');

    Route::get("fullcalendar", "Calender@Chartjs");

    Route::resource("connect", "contectusController");

    Route::resource("view","viewController");

});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','picture'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    function admin(){
        return $this->role=='admin' ? true : false;
    }


}

app/Http/Controllers/Administrator/userController.php
<?php

namespace App\Http\Controllers\Administrator;

use App\Http\Controllers\Controller;
use App\Http\Requests\userRequest;
use App\User;
use App\workgroupModel;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class userController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $u=Auth::user()->id;
        $item_name=DB::table('auth_assignment')->select('item_name')->where("user_id","=",$u)->first()->item_name;
        $menu_count=DB::table('auth_item_child')->where("item_name","=",$item_name)->where("child" ,"=", "view@1")->count();
        if($menu_count != 0) {
        $users=User::latest()->paginate(3);
        return view('admin.user.list_user',compact('users'));
        }else{
            echo '<img src="../../../images/pre/1.jpg" class="imgpre" style="margin-left:265px;margin-top:60px;border-radius: 80px;">';
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $u=Auth::user()->id;
        $item_name=DB::table('auth_assignment')->select('item_name')->where("user_id","=",$u)->first()->item_name;
        $menu_count=DB::table('auth_item_child')->where("item_name","=",$item_name)->where("child" ,"=", "create@1")->count();
        if($menu_count != 0) {
        return view('admin.user.add_user');
        }else{
            echo '<img src="../../../images/pre/1.jpg" class="imgpre" style="margin-left:265px;margin-top:60px;border-radius: 80px;">';
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(userRequest $request)
    {
        $record=new User();
        $record->name=$request->input('name');
        $record->email=$request->input('email');
        if($request->hasFile('picture')){
            $filename=time().'.'.$request->file('picture')->getClientOriginalExtension();
            if($request->file('picture')->move('images/pic',$filename)){
                $record->picture=$filename;
            }
        }
        $record->password=Hash::make($request->input('password'));
        $record->save();
        alert()->success('موفقیت امیز','با موفقیت بروزرسانی  شد');
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request)
    {
        $uss=User::FindOrFail($request->exp_id);
        return view('admin.user.explain_user',compact('uss'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $u=Auth::user()->id;
        $item_name=DB::table('auth_assignment')->select('item_name')->where("user_id","=",$u)->first()->item_name;
        $menu_count=DB::table('auth_item_child')->where("item_name","=",$item_name)->where("child" ,"=", "edit@1")->count();
        if($menu_count != 0) {
        return view('admin.user.edit_use',compact('user'));
        }else{
            echo '<img src="../../../images/pre/1.jpg" class="imgpre" style="margin-left:265px;margin-top:60px;border-radius: 80px;">';
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(userRequest $request,User $user)
    {
        $record =$request->all();
        if($request->hasFile('picture')){
            $filename=time().'.'.$request->file('picture')->getClientOriginalExtension();
            if($request->file('picture')->move('images/pic',$filename)){
                $record['picture'] = $filename;
            }
        }
        $user->update($record);
        $users=User::latest()->paginate(3);
        return view('admin.user.list_user',compact('users'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(User $user)
    {
        $user->delete();
        alert()->success('موفقیت امیز','با موفقیت بروزرسانی  شد');
        return redirect()->back();
    }
    public function explain(){

    }
}

resources/views/admin/user/add_user.blade.php
@extends('layout.index')
@section('css')
    <style type="text/css">
        body {
            font-family: sans-serif;
            background-color: #eeeeee;
        }

        .file-upload {
            background-color: #ffffff;
            width: 600px;
            margin: 0 auto;
            padding: 20px;
        }

        .file-upload-btn {
            width: 100%;
            margin: 0;
            color: #fff;
            background: #1FB264;
            border: none;
            padding: 10px;
            border-radius: 4px;
            border-bottom: 4px solid #15824B;
            transition: all .2s ease;
            outline: none;
            text-transform: uppercase;
            font-weight: 700;
        }

        .file-upload-btn:hover {
            background: #1AA059;
            color: #ffffff;
            transition: all .2s ease;
            cursor: pointer;
        }

        .file-upload-btn:active {
            border: 0;
            transition: all .2s ease;
        }

        .file-upload-content {
            display: none;
            text-align: center;
        }

        .file-upload-input {
            position: absolute;
            margin: 0;
            padding: 0;
            width: 100%;
            height: 100%;
            outline: none;
            opacity: 0;
            cursor: pointer;
        }

        .image-upload-wrap {
            margin-top: 20px;
            border: 4px dashed #1FB264;
            position: relative;
        }

        .image-dropping,
        .image-upload-wrap:hover {
            background-color: #1FB264;
            border: 4px dashed #ffffff;
        }

        .image-title-wrap {
            padding: 0 15px 15px 15px;
            color: #222;
        }

        .drag-text {
            text-align: center;
        }

        .drag-text h3 {
            font-weight: 100;
            text-transform: uppercase;
            color:black;
            padding: 60px 0;
        }

        .file-upload-image {
            max-height: 200px;
            max-width: 200px;
            margin: auto;
            padding: 20px;
        }

        .remove-image {
            width: 200px;
            margin: 0;
            color: #fff;
            background: #cd4535;
            border: none;
            padding: 10px;
            border-radius: 4px;
            border-bottom: 4px solid #b02818;
            transition: all .2s ease;
            outline: none;
            text-transform: uppercase;
            font-weight: 700;
        }

        .remove-image:hover {
            background: #c13b2a;
            color: #ffffff;
            transition: all .2s ease;
            cursor: pointer;
        }

        .remove-image:active {
            border: 0;
            transition: all .2s ease;
        }
    </style>
    <script type="text/javascript">
        function readURL(input) {
            if (input.files && input.files[0]) {

                var reader = new FileReader();

                reader.onload = function(e) {
                    $('.image-upload-wrap').hide();

                    $('.file-upload-image').attr('src', e.target.result);
                    $('.file-upload-content').show();

                    $('.image-title').html(input.files[0].name);
                };

                reader.readAsDataURL(input.files[0]);

            } else {
                removeUpload();
            }
        }

        function removeUpload() {
            $('.file-upload-input').replaceWith($('.file-upload-input').clone());
            $('.file-upload-content').hide();
            $('.image-upload-wrap').show();
        }
        $('.image-upload-wrap').bind('dragover', function () {
            $('.image-upload-wrap').addClass('image-dropping');
        });
        $('.image-upload-wrap').bind('dragleave', function () {
            $('.image-upload-wrap').removeClass('image-dropping');
        });
    </script>
@endsection
@section('content')
    <div class="row">
        <div class="col-sm-6">
            {{Form::open(array('action'=>'Administrator\userController@store','files'=>true,'class'=>'fouser'))}}
            <div class="card" >
                <form action="" method="post">
                    @if(count($errors) >0)
                        <div class="alert alert-danger">
                            <ul>
                                @foreach($errors->all() as $error)
                                    <li>
                                        {{$error}}
                                    </li>
                                    @endforeach
                            </ul>
                        </div>
                    @endif
                <div class="card-header">
                    <strong>اضافه کردن کاربر</strong>
                </div>
                <div class="card-body">
                    <div class="col-lg-6 float-right">
                        {{Form::label('inputname','نام کاربر')}}<i class="fa fa-star" style="font-size: 10px;color: red"></i>
                        {{Form::text('name',null,['class'=>'form-control'])}}
                    </div>

                    <div class="col-lg-6 float-left">
                        {{Form::label('inputname','ایمیل')}}<i class="fa fa-star" style="font-size: 10px;color: red"></i>
                        {{Form::email('email',null,['class'=>'form-control'])}}
                    </div>

                    <div class="file-upload col-lg-12 float-right">
                        {{Form::label('inputname','تصویر کاربر')}}<i class="fa fa-star" style="font-size: 10px;color: red"></i>

                        <div class="image-upload-wrap">

                            <input class="file-upload-input" type='file' name="picture" onchange="readURL(this);" accept="image/*" />
                            <div class="drag-text">
                                <h3><i class="fa fa-upload" aria-hidden="true" style="font-size: 50px;"></i>
                                </h3>
                            </div>
                        </div>
                        <div class="file-upload-content">
                            <img class="file-upload-image" src="#" alt="your image" />
                            <div class="image-title-wrap">
                                <button type="button" onclick="removeUpload()" class="remove-image">حذف <span class="image-title">Uploaded Image</span></button>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 float-right">
                        {{Form::label('inputname','رمزعبور')}}<i class="fa fa-star" style="font-size: 10px;color: red"></i>
                        {{Form::password('password',['class'=>'form-control'])}}
                    </div>

                    <div class="col-lg-6 float-left" style="position: relative;top: 33px;right:500px;">
                        {{Form::button('<i class="fa fa-dot-circle-o"></i> ارسال',['type'=>'submit','class'=>'btn btn-sm btn-primary'])}}

                        {{Form::button('انصراف',['type'=>'reset','class'=>'btn btn-sm btn-danger'])}}
                    </div>

                    <!--/.row-->

                </div>
                </form>
                {{Form::close()}}
            </div>

        </div>

    </div>
@endsection

resources/views/admin/user/edit_use.blade.php
@extends('layout.index')
@section('css')
    <style type="text/css">
        body {
            font-family: sans-serif;
            background-color: #eeeeee;
        }

        .file-upload {
            background-color: #ffffff;
            width: 600px;
            margin: 0 auto;
            padding: 20px;
        }

        .file-upload-btn {
            width: 100%;
            margin: 0;
            color: #fff;
            background: #1FB264;
            border: none;
            padding: 10px;
            border-radius: 4px;
            border-bottom: 4px solid #15824B;
            transition: all .2s ease;
            outline: none;
            text-transform: uppercase;
            font-weight: 700;
        }

        .file-upload-btn:hover {
            background: #1AA059;
            color: #ffffff;
            transition: all .2s ease;
            cursor: pointer;
        }

        .file-upload-btn:active {
            border: 0;
            transition: all .2s ease;
        }

        .file-upload-content {
            display: none;
            text-align: center;
        }

        .file-upload-input {
            position: absolute;
            margin: 0;
            padding: 0;
            width: 100%;
            height: 100%;
            outline: none;
            opacity: 0;
            cursor: pointer;
        }

        .image-upload-wrap {
            margin-top: 20px;
            border: 4px dashed #1FB264;
            position: relative;
        }

        .image-dropping,
        .image-upload-wrap:hover {
            background-color: #1FB264;
            border: 4px dashed #ffffff;
        }

        .image-title-wrap {
            padding: 0 15px 15px 15px;
            color: #222;
        }

        .drag-text {
            text-align: center;
        }

        .drag-text h3 {
            font-weight: 100;
            text-transform: uppercase;
            color:black;
            padding: 60px 0;
        }

        .file-upload-image {
            max-height: 200px;
            max-width: 200px;
            margin: auto;
            padding: 20px;
        }

        .remove-image {
            width: 200px;
            margin: 0;
            color: #fff;
            background: #cd4535;
            border: none;
            padding: 10px;
            border-radius: 4px;
            border-bottom: 4px solid #b02818;
            transition: all .2s ease;
            outline: none;
            text-transform: uppercase;
            font-weight: 700;
        }

        .remove-image:hover {
            background: #c13b2a;
            color: #ffffff;
            transition: all .2s ease;
            cursor: pointer;
        }

        .remove-image:active {
            border: 0;
            transition: all .2s ease;
        }
    </style>
    <script type="text/javascript">
        function readURL(input) {
            if (input.files && input.files[0]) {

                var reader = new FileReader();

                reader.onload = function(e) {
                    $('.image-upload-wrap').hide();

                    $('.file-upload-image').attr('src', e.target.result);
                    $('.file-upload-content').show();

                    $('.image-title').html(input.files[0].name);
                };

                reader.readAsDataURL(input.files[0]);

            } else {
                removeUpload();
            }
        }

        function removeUpload() {
            $('.file-upload-input').replaceWith($('.file-upload-input').clone());
            $('.file-upload-content').hide();
            $('.image-upload-wrap').show();
        }
        $('.image-upload-wrap').bind('dragover', function () {
            $('.image-upload-wrap').addClass('image-dropping');
        });
        $('.image-upload-wrap').bind('dragleave', function () {
            $('.image-upload-wrap').removeClass('image-dropping');
        });
    </script>
@endsection
@section('content')
    <div class="row">
        <div class="col-sm-6">
            {{Form::open(array('url'=>route('user.update',$user->id),'files'=>true,'method'=>'PATCH','class'=>'fouser'))}}
            <div class="card" >
                <form action="" method="post">
                    @if(count($errors) >0)
                        <div class="alert alert-danger">
                            <ul>
                                @foreach($errors->all() as $error)
                                    <li>
                                        {{$error}}
                                    </li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <div class="card-header">
                        <strong>ویرایش  کاربر</strong>
                    </div>
                    <div class="card-body">
                        <div class="col-lg-6 float-right">
                            {{Form::label('inputname','نام کاربر')}}
                            {{Form::text('name',$user->name,['class'=>'form-control'])}}
                        </div>

                        <div class="col-lg-6 float-left">
                            {{Form::label('inputname','ایمیل')}}
                            {{Form::email('email',$user->email,['class'=>'form-control'])}}
                        </div>

                        <div class="file-upload col-lg-12 float-right">
                            {{Form::label('inputname','تصویر کاربر')}}<i class="fa fa-star" style="font-size: 10px;color: red"></i>

                            <div class="image-upload-wrap">

                                <input class="file-upload-input" type='file' name="picture" onchange="readURL(this);" accept="image/*" />
                                <div class="drag-text">
                                    <h3><i class="fa fa-upload" aria-hidden="true" style="font-size: 50px;"></i>
                                    </h3>
                                </div>
                            </div>
                            <div class="file-upload-content">
                                <img class="file-upload-image" src="#" alt="your image" />
                                <div class="image-title-wrap">
                                    <button type="button" onclick="removeUpload()" class="remove-image">حذف <span class="image-title">Uploaded Image</span></button>
                                </div>
                                <img src="../../../images/pic/{{$user->picture}}" alt="" width="50px" height="50px">

                            </div>
                        </div>
                        <div class="col-lg-6 float-right">
                            {{Form::label('inputname','رمزعبور')}}
                            {{Form::password('password',['class'=>'form-control'])}}
                        </div>

                        <div class="col-lg-6 float-left" style="position: relative;top: 33px;right:500px;">
                            {{Form::button('<i class="fa fa-dot-circle-o"></i> ارسال',['type'=>'submit','class'=>'btn btn-sm btn-primary'])}}

                            {{Form::button('انصراف',['type'=>'reset','class'=>'btn btn-sm btn-danger'])}}
                        </div>

                        <!--/.row-->

                    </div>
                </form>
                {{Form::close()}}
            </div>

        </div>

    </div>
@endsection

resources/views/admin/user/explain_user.blade.php
@extends('layout.index')
@section('content')

    <div class="row" style="width: 100%;height: 100%;position: relative;right:16px;font-family: 'B Yekan';font-size:20px;color: #000;">
        <div class="col-lg-12 bg-white">
            <p style="text-align: right;padding-right: 8px;padding-top:8px;box-sizing: border-box">جزئیات کاربر:{{$uss->name}}</p>
            <hr>
        <div class="col-lg-6 float-right" style="padding-top: 20px;box-sizing: border-box">
            <label for="">نام کاربر:{{$uss->name}}</label>
        </div>
        <div class="col-lg-6 float-left" style="padding-top: 20px;box-sizing: border-box">
            <label for="">ایمیل کاربر:{{$uss->email}}</label>
        </div>
<?php
            $pic=$uss->picture
            ?>
    @if($pic==true)
        <div class="col-lg-6 float-right" style="padding-top: 20px;box-sizing: border-box">
            <label for="">تصویرکاربر:<img src="../../images/pic/{{$pic}}" alt="" width="50" height="50">   </label>
        </div>
    @endif
        <div class="col-lg-6 float-left" style="padding-top: 20px;box-sizing: border-box">
            <form action="\admin\user\" style="position:relative;right:500px;top: 50px;">
            <button class="btn btn-primary" style="border-radius: 5px">بازگشت</button>
            </form>
        </div>
    </div>
    </div>
@endsection

resources/views/admin/user/list_user.blade.php
@extends('layout.index')
@section('script')
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="<?php echo url('../js/sort-table.js')?>"></script>
    <script src="<?php echo url('../js/sort-table.min.js')?>"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script>
        $(document).ready(function(){
            $("#myInput").on("keyup", function() {
                var value = $(this).val().toLowerCase();
                $("#myTable tr").filter(function() {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>


@endsection
@section('content')
    <div class="card">

        <div class="card-header">
            <h3 class="card-title" style="font-family: 'B Yekan';text-align: right;"><i class="fa fa-list-alt" style="position: relative;top: 2px;left: 4px;"></i>لیست کاربران</h3>

            <a href="\admin\user\create"><button type="button" class="bg bg-success" style="border-radius: 5px;"> <i class="fa fa-plus" aria-hidden="true"></i></button></a>



        </div>
        <!-- /.card-header -->

        <div class="card-body">
            <div class="row">

                <div class="col-lg-6" style="float: left!important;">
                    <input class="form-control" id="myInput" type="text" placeholder="جستجو...." style="margin-bottom: 20px;font-family: 'B Yekan'">
                </div>
            </div>
            <?php $tbl=DB::table('users')->get(); ?>
            @if(count($tbl)>=1)
                <table  class="table table-bordered table-striped js-sort-table"  id="demo1">
                    <thead>
                    <tr>
                        <th>نام کاربری</th>
                        <th>ایمیل</th>
                        <th>تصویر </th>
                        <th>سطح دسترسی</th>
                        <th>عملیات</th>
                    </tr>
                    </thead>

                    <tbody id="myTable" class="sortable">
                    @foreach($users as $use)
                        <tr>
                            <td>{{$use->name}}</td>
                            <td>{{$use->email}}</td>
                            <td><img src="../../images/pic/{{$use->picture}}" alt="" width="50" height="50"></td>
                            <td>{{$use->role}}</td>
                            <td style="width: 12%">
                                <form action="{{route('user.edit',$use->id)}}" style="width: 2%;">
                                    <button type="submit" class="btn btn-success" style="border-radius: 5px">
                                        <i class="fa fa-edit"></i>
                                    </button>
                                </form>
                                <form action="{{route('user.destroy',$use->id)}}" id="closee" method="post" style="width: 2%;">
                                    {{@method_field('delete')}}
                                    {{@csrf_field()}}
                                    <button type="submit" class="btn btn-danger" style="border-radius: 5px;position: relative;top: 13px;">
                                        <i class="fa fa-trash-o"></i>
                                    </button>
                                </form>
                                @if(! empty($_GET['item_name']))
                                    <form action="\admin\premesion\" id="closee" method="post" style="width: 2%;">
                                        {{@method_field('post')}}
                                        {{@csrf_field()}}
                                        <input type="hidden" name="user_id" value="{{$use->id}}">
                                        <input type="hidden" name="item_name" value="{{$_GET['item_name']}}">
                                        <button type="submit" class="btn btn-danger" style="border-radius: 5px">
                                            <i class="fa fa-plus"></i>
                                        </button>
                                    </form>
                                @endif
                                <form action="\admin\user\show" id="closee" method="get" style="width: 2%;">
                                    {{@method_field('get')}}
                                    {{@csrf_field()}}
                                    <input type="hidden" name="exp_id" value="{{$use->id}}">
                                    <button type="submit" class="btn btn-primary" style="border-radius: 5px;position: relative;top: -22px;right: 48px;">
                                        <i class="fa fa-plus"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                    <tfoot>
                    <tr>
                        <th>نام کاربری</th>
                        <th>ایمیل</th>
                        <th>تصویر </th>
                        <th>سطح دسترسی</th>
                        <th>عملیات</th>
                    </tr>
                    </tfoot>
                </table>
            @else
                <p style="font-family: 'B Yekan'">چیزی برای نمایش وجود ندارد</p>
            @endif
        </div>
        <ul class="pagination">
            {{$users->links()}}
        </ul>
        <!-- /.card-body -->
    </div>

@stop